export const LIVE_JS = `
(function(){
  "use strict";
  var PAUSE_LIMIT=256,MAX_TURNS=500,TERMINAL={completed:1,failed:1,cancelled:1};
  var state={snapshot:{schemaVersion:1,cursor:null,projects:[],sessions:[]},events:[],project:null,selected:null,node:null,browserLevel:"projects",paused:false,pending:[],overflow:false,source:null,lastAt:0,active:false,positions:{},pinned:{},seen:{},camera:{x:24,y:24,k:1},cameraEpoch:0,fitFor:null,pointer:null,playback:{mode:"live",events:[],items:[],index:0,playing:false,speed:1,timer:null,startAt:null,endAt:null,truncated:false,gap:false},transcript:{source:null,turns:[],seen:{},query:"",follow:true,unread:0,status:"idle",session:null}};
  function el(id){return document.getElementById(id);}
  function esc(s){return String(s==null?"":s).replace(/[&<>"']/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c];});}
  function short(s,n){s=String(s||"");return s.length>n?s.slice(0,n-1)+"…":s;}
  function title(s){return String(s||"activity").replace(/[._-]+/g," ").replace(/\\b\\w/g,function(c){return c.toUpperCase();});}
  function ago(v){var at=Date.parse(v||""),ms=Date.now()-at;if(!Number.isFinite(ms))return"";var s=Math.max(0,Math.round(ms/1000));if(s<5)return"just now";if(s<60)return s+"s ago";var m=Math.round(s/60);return m<60?m+"m ago":Math.round(m/60)+"h ago";}
  function providerOf(v){var p=String(v&&v.provider||v&&v.host||"").toLowerCase();if(p.includes("claude")||p.includes("anthropic"))return"claude";if(p.includes("codex")||p.includes("openai"))return"codex";if(p.includes("ruflo"))return"ruflo";if(p.includes("aqe"))return"aqe";return"local";}
  function providerName(v){return{claude:"Claude",codex:"Codex",ruflo:"ruflo",aqe:"Agentic QE",local:"Local"}[providerOf(v)];}
  function providerGlyph(v){return{claude:"✳",codex:"◉",ruflo:"R",aqe:"Q",local:"⌁"}[providerOf(v)];}
  function kindName(k){return{session:"Coordinator",agent:"Agent",subagent:"Worker",tool:"Tool",skill:"Skill",plugin:"Plugin",mcp:"MCP tool",gate:"Quality gate"}[k]||title(k||"agent");}
  function statusText(v){return{running:"Working",queued:"Queued",quiescent:"Waiting",expired:"No recent activity",blocked:"Blocked",completed:"Completed",failed:"Failed",cancelled:"Cancelled",idle:"Waiting"}[v]||"Outcome unavailable";}
  function label(n){return n&&(n.toolName||n.label||n.toolCategory||n.role&&title(n.role)||kindName(n.kind))||"Activity";}
  function actionText(a,n,s){if(a==="tool.started")return label(n)+" started";if(a==="tool.completed")return label(n)+(s==="failed"?" failed":" completed");return{"session.started":"Session started","session.input":"New input","agent.output":"Response produced","agent.spawned":"Worker dispatched","agent.planned":"Agent scheduled","session.completed":"Session completed","session.failed":"Session failed"}[a]||title(a);}
  function sessionsOf(v){var x=v&&v.snapshot?v.snapshot:v;return x&&Array.isArray(x.sessions)?x:{schemaVersion:1,cursor:null,projects:[],sessions:[]};}
  function setConnection(k,t){el("live-state-dot").dataset.state=k;el("live-state-text").textContent=t;el("live-browser-state-dot").dataset.state=k;el("live-browser-state").textContent=t;}
  function sessionKey(s){return String(s&&s.key||((s&&s.host||providerOf(s))+":"+(s&&s.id||"")));}
  function isLiveSession(s){return!!s&&s.status==="running"&&s.lifecycle==="active";}
  function sessionState(s){var key=s&&s.status||"unknown",life=s&&s.lifecycle||"historical";if(key==="failed"||key==="cancelled"||key==="completed"||key==="blocked"||key==="queued")return{key:key,label:statusText(key)};if(life==="active"&&key==="running")return{key:"working",label:"Working now"};if(life==="quiescent")return{key:"waiting",label:"Waiting for activity"};if(life==="expired")return{key:"stale",label:"No recent activity"};if(life==="historical"&&key==="running")return{key:"stale",label:"Last seen working"};return{key:"historical",label:"Last active"};}
  function entityState(n,s){var key=n&&n.status||"unknown";if(key==="failed"||key==="cancelled"||key==="completed"||key==="blocked"||key==="queued")return{key:key,label:statusText(key)};if(key==="running"&&isLiveSession(s))return{key:"working",label:n&&({tool:1,skill:1,plugin:1,mcp:1})[n.kind]?"Running":"Working"};if(key==="running")return{key:"stale",label:"Last seen working"};if(key==="quiescent")return{key:"waiting",label:"Waiting"};if(key==="expired")return{key:"stale",label:"No recent activity"};return{key:"historical",label:"Activity recorded"};}
  function sessionById(id){return state.snapshot.sessions.find(function(s){return sessionKey(s)===id||s.id===id;});}
  function projectName(s){return s&&s.project&&s.project!=="unknown"?s.project:"Project not reported";}
  function rootSession(s){var seen={};while(s&&s.parentSessionId&&!seen[sessionKey(s)]){seen[sessionKey(s)]=1;var parent=state.snapshot.sessions.find(function(candidate){return candidate.host===s.host&&candidate.id===s.parentSessionId;});if(!parent)break;s=parent;}return s;}
  function childSessions(root){if(!root)return[];var descendants=[],frontier=[root.id],seen={};seen[sessionKey(root)]=1;while(frontier.length){var parent=frontier.shift();state.snapshot.sessions.forEach(function(s){if(s.host===root.host&&s.parentSessionId===parent&&!seen[sessionKey(s)]){seen[sessionKey(s)]=1;descendants.push(s);frontier.push(s.id);}});}return descendants.sort(function(a,b){var ar=isLiveSession(a)?0:1,br=isLiveSession(b)?0:1;return ar-br||Date.parse(b.updatedAt||0)-Date.parse(a.updatedAt||0);});}
  function isNavigationRoot(s){return!!s&&(s.navigationRoot===true||(s.navigationRoot!==false&&rootSession(s)===s));}
  function visibleSessions(){return state.snapshot.sessions.filter(function(s){return isNavigationRoot(s)&&String(s.projectKey||projectName(s))===state.project;}).sort(function(a,b){var ar=isLiveSession(a)?0:1,br=isLiveSession(b)?0:1;return ar-br||Date.parse(b.updatedAt||0)-Date.parse(a.updatedAt||0);});}
  function receiveSnapshot(v,reset){state.snapshot=sessionsOf(v);state.lastAt=Date.now();if(reset){state.events=[];state.positions={};state.seen={};state.node=null;state.fitFor=null;}var projects=projectCatalog();if(!projects.some(function(p){return p.id===state.project;}))state.project=projects[0]&&projects[0].id||null;if(!sessionById(state.selected)||String(sessionById(state.selected).projectKey||projectName(sessionById(state.selected)))!==state.project){var list=visibleSessions();selectSession(list[0]&&sessionKey(list[0]),true);}render();}
  function applyEvent(ev){
    if(!ev||!ev.sessionId||!ev.actor||!ev.actor.id)return;if(ev.eventId&&state.seen[ev.eventId])return;
    var sessions=state.snapshot.sessions.slice(),evKey=String(ev.sessionKey||ev.host+":"+ev.sessionId),i=sessions.findIndex(function(s){return sessionKey(s)===evKey;}),s=i>=0?Object.assign({},sessions[i]):{id:ev.sessionId,key:evKey,project:ev.project,projectKey:ev.projectKey,host:ev.host,status:"unknown",nodes:[],edges:[]};if(ev.parentSessionId)s.parentSessionId=ev.parentSessionId;
    s.nodes=(s.nodes||[]).slice();s.edges=(s.edges||[]).slice();var targetTerminal=!!ev.target&&/\\.(completed|failed|cancelled)$/.test(ev.action||""),priorActor=s.nodes.find(function(n){return n.id===ev.actor.id;});
    function upsert(a,status){var at=s.nodes.findIndex(function(n){return n.id===a.id;}),old=at>=0?s.nodes[at]:{},next=Object.assign({},old,{id:a.id,kind:a.kind||old.kind,role:a.role||old.role,provider:a.provider||old.provider,model:a.model||old.model,label:a.label||old.label,toolName:a.toolName||old.toolName,host:ev.host||old.host,surface:ev.surface||old.surface,status:status||old.status,observedAt:ev.observedAt,confidence:ev.source&&ev.source.confidence||old.confidence,lastAction:ev.action,durationMs:ev.attributes&&ev.attributes.durationMs||old.durationMs});if(TERMINAL[old.status]&&!TERMINAL[next.status])next.status=old.status;if(at>=0)s.nodes[at]=next;else s.nodes.push(next);}
    upsert(ev.actor,targetTerminal?priorActor&&priorActor.status||"running":ev.status);if(ev.target&&ev.target.id){upsert(Object.assign({},ev.target,{label:ev.attributes&&(ev.attributes.toolName||ev.attributes.toolCategory)||ev.target.label,toolName:ev.attributes&&ev.attributes.toolName}),targetTerminal?ev.status:"running");var eid=ev.actor.id+"|"+ev.action+"|"+ev.target.id,edge={id:eid,source:ev.actor.id,target:ev.target.id,action:ev.action,confidence:ev.source&&ev.source.confidence},ei=s.edges.findIndex(function(x){return x.id===eid;});if(ei>=0)s.edges[ei]=edge;else s.edges.push(edge);}
    if(ev.actor.kind==="session"&&/^session\\./.test(ev.action||""))s.status=ev.status;if(ev.status==="running"&&(!ev.source||ev.source.adapter!=="codex-state"))s.lifecycle="active";else if(!s.lifecycle)s.lifecycle="historical";s.updatedAt=ev.observedAt;if(i>=0)sessions[i]=s;else sessions.push(s);
    state.snapshot={schemaVersion:state.snapshot.schemaVersion||1,cursor:ev.eventId||state.snapshot.cursor,projects:state.snapshot.projects,sessions:sessions,health:state.snapshot.health};if(ev.eventId)state.seen[ev.eventId]=1;state.events.unshift(ev);state.events=state.events.slice(0,100);state.lastAt=Date.now();if(!state.selected)selectSession(sessionKey(s),false);if(state.playback.mode==="live")render();
  }
  function receive(k,d){if(state.paused){if(state.pending.length<PAUSE_LIMIT)state.pending.push({kind:k,data:d});else{state.pending=[];state.overflow=true;}return;}if(k==="delta"&&!d.snapshot)applyEvent(d&&d.event?d.event:d);else receiveSnapshot(d,k==="reset"||!!(d&&d.reset));}
  function connect(){setConnection("connecting","Loading current work…");fetch("/api/live",{cache:"no-store"}).then(function(r){if(!r.ok)throw Error();return r.json();}).then(function(d){receiveSnapshot(d);openStream();}).catch(function(){setConnection("offline","Live telemetry unavailable.");});}
  function openStream(){if(state.source)state.source.close();if(!window.EventSource)return;var src=new EventSource("/api/live/events");state.source=src;src.onopen=function(){setConnection(state.paused?"paused":"live",state.paused?"Updates paused":"Live · following agent activity");};["init","reset","delta"].forEach(function(k){src.addEventListener(k,function(e){try{receive(k,JSON.parse(e.data));}catch(_){}});});src.onerror=function(){setConnection("offline","Connection interrupted · reconnecting…");};}
  function graphData(s){
    var all=s&&s.nodes||[],edges=s&&s.edges||[],isTool={tool:1,skill:1,plugin:1,mcp:1},allTools=all.filter(function(n){return isTool[n.kind];}),nodes=all.filter(function(n){return!isTool[n.kind];}),owner={},history={};
    edges.forEach(function(e){var t=allTools.find(function(n){return n.id===e.target;}),src=allTools.find(function(n){return n.id===e.source;});if(t)owner[t.id]=e.source;if(src)owner[src.id]=e.target;});
    allTools.forEach(function(t){if(!owner[t.id])owner[t.id]=(nodes.find(function(n){return n.kind==="agent"||n.kind==="subagent"||n.kind==="session";})||{}).id;});
    var byOwner={};allTools.forEach(function(t){var o=owner[t.id]||"unowned";(byOwner[o]||(byOwner[o]=[])).push(t);});var tools=[];Object.keys(byOwner).forEach(function(o){var group=byOwner[o].sort(function(a,b){var ar=a.status==="running"?0:1,br=b.status==="running"?0:1;return ar-br||Date.parse(b.observedAt||0)-Date.parse(a.observedAt||0);}),active=group.filter(function(t){return t.status==="running";}),recent=group.filter(function(t){return t.status!=="running";}).slice(0,6);tools=tools.concat(active,recent);history[o]=Math.max(0,group.length-active.length-recent.length);});
    var visible={};nodes.slice(0,80).forEach(function(n){visible[n.id]=1;});return{nodes:nodes.slice(0,80),tools:tools.slice(0,80),owner:owner,history:history,totalTools:allTools.length,edges:edges.filter(function(e){return visible[e.source]&&visible[e.target];})};
  }
  function layout(s,nodes,force){var key=s?s.id:"none",out=force?{}:state.positions[key]||{},edges=s&&s.edges||[],parents={};edges.forEach(function(e){parents[e.target]=e.source;});var levels={};function depth(id,seen){if(levels[id]!=null)return levels[id];if(seen[id])return 0;seen[id]=1;var p=parents[id],d=p?1+depth(p,seen):0;return levels[id]=Math.min(d,5);}var groups={};nodes.forEach(function(n){var d=depth(n.id,{});(groups[d]||(groups[d]=[])).push(n);});Object.keys(groups).forEach(function(k){var group=groups[k],column=Number(k),step=Math.max(150,Math.min(230,720/Math.max(1,group.length)));group.forEach(function(n,i){if(!out[n.id])out[n.id]={x:125+column*270,y:100+(i-(group.length-1)/2)*step+300};});});state.positions[key]=out;return out;}
  function edgePath(a,b){var dx=b.x-a.x,dy=b.y-a.y,bend=Math.min(110,Math.max(45,Math.abs(dx)*.35));return"M"+a.x+" "+a.y+" C"+(a.x+(dx>=0?bend:-bend))+" "+a.y+" "+(b.x-(dx>=0?bend:-bend))+" "+b.y+" "+b.x+" "+b.y;}
  function toolPosition(owner,index,count){var row=index-(count-1)/2;return{x:owner.x+150,y:owner.y+row*48};}
  function kindShape(k){if(k==="session")return'<circle class="node-core node-core-ring" r="18"></circle><circle class="node-core-dot" r="5"></circle>';if(k==="gate")return'<path class="node-core" d="M0-21L19-10V10L0 21-19 10V-10Z"></path><path class="node-core-mark" d="M-7 0l5 5L8-7"></path>';return'<path class="node-core" d="M0-22L19-11V11L0 22-19 11V-11Z"></path><circle class="node-core-dot" r="5"></circle>';}
  function renderGraph(s,force){
    var d=graphData(s),pos=layout(s,d.nodes,force),selected=state.node,related={};if(selected){related[selected]=1;(s&&s.edges||[]).forEach(function(e){if(e.source===selected)related[e.target]=1;if(e.target===selected)related[e.source]=1;});}
    var toolGroups={};d.tools.forEach(function(t){var o=d.owner[t.id];if(o)(toolGroups[o]||(toolGroups[o]=[])).push(t);});var tp={};
    Object.keys(toolGroups).forEach(function(o){var at=pos[o];if(at)toolGroups[o].forEach(function(t,i){tp[t.id]=toolPosition(at,i,toolGroups[o].length);});});
    var edges=d.edges.map(function(e){var a=pos[e.source],b=pos[e.target];if(!a||!b)return"";var active=isLiveSession(s)&&(s.nodes||[]).some(function(n){return(n.id===e.source||n.id===e.target)&&entityState(n,s).key==="working";}),rel=!selected||e.source===selected||e.target===selected,path=edgePath(a,b);return'<path id="edge-'+esc(e.id)+'" class="live-edge" data-source="'+esc(e.source)+'" data-target="'+esc(e.target)+'" data-active="'+active+'" data-related="'+rel+'" d="'+path+'"></path>'+(active?'<circle class="live-flow-dot" r="2.5"><animateMotion dur="1.5s" repeatCount="indefinite" path="'+path+'"></animateMotion></circle>':"");}).join("");
    Object.keys(toolGroups).forEach(function(o){var a=pos[o];toolGroups[o].forEach(function(t){var b=tp[t.id];if(!a||!b)return;var path="M"+(a.x+28)+" "+a.y+" C"+(a.x+70)+" "+a.y+" "+(b.x-96)+" "+b.y+" "+(b.x-78)+" "+b.y,active=entityState(t,s).key==="working",rel=!selected||selected===o||selected===t.id;edges+='<path class="live-edge live-tool-edge" data-source="'+esc(o)+'" data-target="'+esc(t.id)+'" data-active="'+active+'" data-related="'+rel+'" d="'+path+'"></path>'+(active?'<circle class="live-flow-dot" r="2"><animateMotion dur="1.1s" repeatCount="indefinite" path="'+path+'"></animateMotion></circle>':"");});});
    var nodes=d.nodes.map(function(n){var p=pos[n.id],sel=selected===n.id,rel=!selected||!!related[n.id],pin=!!state.pinned[(s?s.id:"")+"|"+n.id],view=entityState(n,s),meta=n.model&&n.model!=="unknown"?n.model:view.label,work=view.key==="working"?actionText(n.lastAction,n,n.status):view.label,past=d.history[n.id]||0;return'<g class="live-node" tabindex="0" role="button" data-node="'+esc(n.id)+'" data-kind="'+esc(n.kind||"agent")+'" data-status="'+esc(view.key)+'" data-selected="'+sel+'" data-related="'+rel+'" data-pinned="'+pin+'" aria-label="'+esc(label(n)+", "+kindName(n.kind)+", "+view.label)+'" transform="translate('+p.x+" "+p.y+')"><circle class="node-aura" r="42"></circle>'+kindShape(n.kind)+'<circle class="node-status" cx="25" cy="-22" r="4"></circle><text class="node-name" text-anchor="middle" y="48">'+esc(short(label(n),20))+'</text><text class="node-eyebrow" text-anchor="middle" y="63">'+esc(short((kindName(n.kind)+" · "+providerName(n)).toUpperCase(),26))+'</text><g class="node-work" transform="translate(34 -55)"><rect width="154" height="37" rx="18"></rect><circle cx="14" cy="18.5" r="3"></circle><text x="25" y="16">'+esc(short(work,24))+'</text><text class="node-meta" x="25" y="28">'+esc(short(meta,27))+'</text></g>'+(past?'<g class="node-history" transform="translate(34 76)"><rect width="116" height="24" rx="12"></rect><text x="12" y="16">'+past+' earlier operations</text></g>':"")+"</g>";}).join("");
    var tools=d.tools.map(function(t){var p=tp[t.id];if(!p)return"";var rel=!selected||selected===t.id||selected===d.owner[t.id],view=entityState(t,s),elapsed=Number.isFinite(t.durationMs)?(t.durationMs<1000?t.durationMs+" ms":(t.durationMs/1000).toFixed(1)+" s"):"";return'<g class="live-tool" tabindex="0" role="button" data-node="'+esc(t.id)+'" data-owner="'+esc(d.owner[t.id]||"")+'" data-kind="'+esc(t.kind||"tool")+'" data-status="'+esc(view.key)+'" data-related="'+rel+'" aria-label="'+esc(label(t)+", "+kindName(t.kind)+", "+view.label)+'" transform="translate('+p.x+" "+p.y+')"><rect class="live-tool-halo" x="-86" y="-21" width="172" height="42" rx="21"></rect><rect class="live-tool-card" x="-80" y="-17" width="160" height="34" rx="17"></rect><path class="live-tool-icon" d="M-66-1L-61-6-56-1-61 4Z"></path><text class="tool-name" x="-48" y="-2">'+esc(short(label(t),20))+'</text><text class="tool-state" x="-48" y="10">'+esc(short(view.label+(elapsed?" · "+elapsed:""),24))+"</text></g>";}).join("");
    el("live-edges").innerHTML=edges;el("live-nodes").innerHTML=nodes;el("live-tools").innerHTML=tools;el("live-empty").hidden=d.nodes.length>0;el("live-graph-summary").textContent=d.nodes.length+" agents · "+d.totalTools+" operations · "+d.edges.length+" handoffs";applyCamera();renderSelection(s,d);
  }
  function applyCamera(){el("live-viewport").setAttribute("transform","translate("+state.camera.x+" "+state.camera.y+") scale("+state.camera.k+")");el("live-zoom").textContent=Math.round(state.camera.k*100)+"%";}
  function setZoom(next,cx,cy){state.cameraEpoch++;var c=el("live-canvas"),r=c.getBoundingClientRect(),x=cx==null?r.width/2:cx-r.left,y=cy==null?r.height/2:cy-r.top,k=Math.max(.25,Math.min(2.8,next)),wx=(x-state.camera.x)/state.camera.k,wy=(y-state.camera.y)/state.camera.k;state.camera={x:x-wx*k,y:y-wy*k,k:k};applyCamera();}
  function fit(selector){var root=el(selector||"live-viewport"),box;try{box=root.getBBox();}catch(_){return;}if(!box.width&&!box.height)return;var c=el("live-canvas"),p=42,k=Math.max(.25,Math.min(2.5,Math.min((c.clientWidth-p*2)/Math.max(1,box.width),(c.clientHeight-p*2)/Math.max(1,box.height))));state.camera={k:k,x:(c.clientWidth-box.width*k)/2-box.x*k,y:(c.clientHeight-box.height*k)/2-box.y*k};applyCamera();}
  function fitSelection(){if(!state.node){fit();return;}var n=el("live-graph").querySelector('[data-node="'+CSS.escape(state.node)+'"]');if(!n)return;var b=n.getBBox(),c=el("live-canvas"),k=Math.min(2.2,Math.max(1,state.camera.k));state.camera={k:k,x:c.clientWidth/2-(b.x+b.width/2)*k,y:c.clientHeight/2-(b.y+b.height/2)*k};applyCamera();}
  function updateGeometry(id){var s=sessionById(state.selected),p=state.positions[s?s.id:"none"]||{},g=el("live-graph").querySelector('[data-node="'+CSS.escape(id)+'"]');if(g&&p[id])g.setAttribute("transform","translate("+p[id].x+" "+p[id].y+")");renderGraph(s);}
  function renderSelection(s,d){var value=(d.nodes.concat(d.tools)).find(function(n){return n.id===state.node;}),box=el("live-selection-body");if(!value){box.textContent="Select an agent or tool in the map.";return;}var view=entityState(value,s),elapsed=Number.isFinite(value.durationMs)?(value.durationMs<1000?value.durationMs+" ms":(value.durationMs/1000).toFixed(1)+" s"):"Not available",owner=d.owner[value.id],ownerNode=d.nodes.find(function(n){return n.id===owner;}),fields=[["Type",kindName(value.kind)],["State",view.label],["Provider",providerName(value)],["Owner",ownerNode?label(ownerNode):"Not applicable"],["Elapsed",elapsed],["Current work",view.key==="working"?actionText(value.lastAction,value,value.status):view.label],["Evidence",value.confidence||"not reported"]];box.innerHTML="<strong>"+esc(label(value))+"</strong><dl>"+fields.map(function(x){return"<dt>"+esc(x[0])+"</dt><dd>"+esc(x[1])+"</dd>";}).join("")+"</dl>";}
  function projectCatalog(){var given=Array.isArray(state.snapshot.projects)?state.snapshot.projects:[],by={};state.snapshot.sessions.forEach(function(s){var id=String(s.projectKey||projectName(s)),p=by[id]||(by[id]={id:id,name:projectName(s),sessionCount:0,childSessionCount:0,liveCount:0,updatedAt:s.updatedAt});if(isNavigationRoot(s)){p.sessionCount++;if(isLiveSession(s))p.liveCount++;}else p.childSessionCount++;if(Date.parse(s.updatedAt||0)>Date.parse(p.updatedAt||0))p.updatedAt=s.updatedAt;});given.forEach(function(p){var id=String(p.id||p.key||p.projectKey||p.label||p.name),derived=by[id]||{},name=p.label||p.name||p.project||derived.name||"Project not reported";by[id]=Object.assign({},p,derived,{id:id,name:name});});return Object.keys(by).map(function(k){return by[k];}).sort(function(a,b){return Number(b.liveCount||0)-Number(a.liveCount||0)||Date.parse(b.updatedAt||0)-Date.parse(a.updatedAt||0)||a.name.localeCompare(b.name);});}
  function duration(s){var start=s.startedAt||s.createdAt,end=s.endedAt||s.completedAt||((s.status==="completed"||s.status==="failed"||s.status==="cancelled")&&s.updatedAt),a=Date.parse(start||""),b=Date.parse(end||""),ms=b-a;if(!Number.isFinite(a)||!Number.isFinite(b)||ms<=0)return ago(s.updatedAt)||"activity time unavailable";var m=Math.max(1,Math.round(ms/60000));return m<60?m+"m":Math.floor(m/60)+"h "+m%60+"m";}
  function sessionMarkup(s,child){var live=isLiveSession(s),key=sessionKey(s),view=sessionState(s);return'<button class="live-session'+(child?" live-session-child":"")+'" type="button" role="listitem" data-session="'+esc(s.id)+'" data-key="'+esc(key)+'" data-live="'+live+'" data-state="'+esc(view.key)+'" aria-current="'+(key===state.selected)+'"><span class="live-provider" data-provider="'+esc(providerOf(s))+'" aria-hidden="true">'+esc(child?"↳":providerGlyph(s))+'</span><span class="live-session-main">'+esc(short(s.title||s.summary||(child?"Worker thread":providerName(s)+" session"),31))+'</span><span class="live-session-provider"><i data-status="'+esc(view.key)+'"></i>'+esc(child?"Sub-agent · "+providerName(s):providerName(s))+" · "+esc(view.label)+" · "+esc(duration(s))+"</span></button>";}
  function renderSessions(){var projects=projectCatalog(),list=visibleSessions(),current=projects.find(function(p){return p.id===state.project;}),selected=sessionById(state.selected),browser=el("live-browser"),liveSessions=state.snapshot.sessions.filter(isLiveSession),liveProjects=projects.filter(function(p){return Number(p.liveCount)>0;});browser.dataset.level=state.browserLevel;el("live-sub").textContent=liveSessions.length?liveSessions.length+" active session"+(liveSessions.length===1?"":"s")+" across "+liveProjects.length+" project"+(liveProjects.length===1?"":"s"):"No active sessions · browse retained local evidence";el("live-browser-kicker").textContent=state.browserLevel==="sessions"?"PROJECT":"WORKSPACES";el("live-browser-title").textContent=state.browserLevel==="sessions"&&current?short(current.name,26):"Projects";el("live-project-count").textContent=String(projects.length);el("live-project-list").innerHTML=projects.map(function(p){var live=Number(p.liveCount||0),workers=Number(p.childSessionCount||0);return'<button class="live-project" type="button" role="listitem" data-project="'+esc(p.id)+'" data-live="'+(live>0)+'" aria-current="'+(p.id===state.project)+'"><span>'+esc(short(p.name,34))+'</span><small>'+(live?'<b>'+live+' WORKING</b> · ':"")+Number(p.sessionCount||0)+" sessions"+(workers?" · "+workers+" workers":"")+" · "+esc(ago(p.updatedAt)||"activity time unavailable")+"</small></button>";}).join("")||'<div class="live-browser-empty">No local projects found yet.</div>';var selectedRoot=rootSession(selected);if(!selectedRoot||!list.some(function(s){return sessionKey(s)===sessionKey(selectedRoot);})){selectSession(list[0]&&sessionKey(list[0]),true);list=visibleSessions();selected=sessionById(state.selected);selectedRoot=rootSession(selected);}el("live-session-heading").textContent=current?short(current.name,36):"Sessions";el("live-count").textContent=String(list.length);el("live-session-list").innerHTML=list.map(function(s){var children=sessionKey(s)===sessionKey(selectedRoot)?childSessions(s):[];return'<div class="live-session-family">'+sessionMarkup(s,false)+(children.length?'<div class="live-session-children" role="group" aria-label="Sub-agent threads">'+children.map(function(child){return sessionMarkup(child,true);}).join("")+"</div>":"")+"</div>";}).join("")||'<div class="live-browser-empty">No retained sessions for this project.</div>';el("live-session-context-provider").textContent=selected?providerName(selected):"—";el("live-session-context-project").textContent=selected?projectName(selected):"Choose a session";var selectedState=sessionState(selected);el("live-session-context-status").textContent=selected?selectedState.label+" · "+duration(selected):"Waiting for local evidence";}
  function renderHealth(){var h=state.snapshot.health||{},bad=0;el("live-health").innerHTML=Object.keys(h).sort().map(function(n){var v=h[n]||{};if(v.status==="error")bad++;return'<span class="live-health-item" data-status="'+esc(v.status||"unknown")+'"><b>'+esc(n)+'</b> · '+esc(v.status||"unknown")+" · "+Number(v.files||0)+" files · "+Number(v.events||0)+" events · "+Number(v.errors||0)+" errors</span>";}).join("");el("live-health-toggle").textContent=bad?bad+" source issue"+(bad===1?"":"s"):"Sources";}
  function render(){renderSessions();renderHealth();el("live-cursor").textContent=state.snapshot.cursor||"";var source=sessionById(state.selected),s=state.playback.mode==="review"&&state.playback.session||source;renderGraph(s);renderPlayback();if(s&&state.fitFor!==sessionKey(s)){state.fitFor=sessionKey(s);(window.requestAnimationFrame||setTimeout)(function(){fit();});}}
  function closeTranscript(){if(state.transcript.source)state.transcript.source.close();state.transcript.source=null;state.transcript.status="idle";}
  function transcriptStatus(k,t){state.transcript.status=k;var e=el("live-transcript-state");e.dataset.state=k;e.textContent=t;}
  function transcriptItems(v){if(Array.isArray(v))return v;if(v&&v.snapshot&&Array.isArray(v.snapshot.events))return v.snapshot.events;if(v&&Array.isArray(v.events))return v.events;if(v&&Array.isArray(v.items))return v.items;if(v&&Array.isArray(v.turns))return v.turns;if(v&&v.item)return[v.item];if(v&&v.turn)return[v.turn];return v&&typeof v==="object"?[v]:[];}
  function normalizeTurn(v){var type=String(v.role||v.type||v.kind||"event").toLowerCase(),role=type.includes("thinking")||type.includes("reason")?"thinking":type.includes("error")?"error":type.includes("tool_result")||type.includes("tool-result")||type.includes("result")?"tool_result":type.includes("tool")||v.tool||v.command||v.patch||v.arguments||v.args?"tool":type.includes("user")?"user":type.includes("assistant")||type.includes("agent")?"assistant":"event",agent=String(v.agentId||v.agent&&v.agent.id||v.actorId||v.actor&&v.actor.id||""),parts=[];
    function part(name,value){if(value==null||value==="")return;var text=value;if(typeof value==="object"){try{text=JSON.stringify(value,null,2);}catch(_){text="[structured content]";}}text=String(text);if(parts.some(function(p){return p.text===text;}))return;parts.push({name:name,text:text});}
    part("",v.content??v.text??v.message??v.body??v.summary);part("Details",v.details);part("Reasoning",v.reasoning);part("Command",v.command);part("Arguments",v.arguments??v.args??v.input);part("Patch",v.patch??v.diff);part("Result",v.result??v.output);part("Error",v.error??v.errorMessage);
    var tool=v.tool||{},toolLabel=tool.name||tool.category,content=parts.map(function(p){return(p.name?p.name+"\\n":"")+p.text;}).join("\\n\\n");if(!content&&toolLabel)content=statusText(tool.status);return{id:String(v.id||v.eventId||tool.callId||[v.timestamp||v.observedAt||"",role,agent,content.slice(0,80)].join("|")),role:role,content:content,agent:agent,label:String(v.label||v.toolName||v.name||toolLabel||role),at:v.timestamp||v.observedAt||v.at||"",tool:tool};}
  function addTranscript(v,reset){if(reset){state.transcript.turns=[];state.transcript.seen={};}transcriptItems(v).forEach(function(raw){var t=normalizeTurn(raw);if(!t.content||state.transcript.seen[t.id])return;state.transcript.seen[t.id]=1;state.transcript.turns.push(t);});if(state.transcript.turns.length>MAX_TURNS)state.transcript.turns=state.transcript.turns.slice(-MAX_TURNS);renderTranscript(true);}
  function openTranscript(s){closeTranscript();state.transcript.session=s&&sessionKey(s);state.transcript.turns=[];state.transcript.seen={};state.transcript.unread=0;renderTranscript();if(!s||!window.EventSource)return;var url="/api/live/transcripts/"+encodeURIComponent(s.host||providerOf(s))+"/"+encodeURIComponent(s.id)+"/events",src=new EventSource(url);state.transcript.source=src;transcriptStatus("connecting","Connecting");src.onopen=function(){transcriptStatus("live","Live");};src.onmessage=function(e){try{addTranscript(JSON.parse(e.data));}catch(_){}};["init","reset","turn","message","delta"].forEach(function(k){src.addEventListener(k,function(e){try{var d=JSON.parse(e.data);addTranscript(d,k==="reset"||!!d.reset);}catch(_){}});});src.onerror=function(){transcriptStatus("error","Unavailable");};}
  function renderTranscript(arrived){var s=sessionById(state.selected),q=state.transcript.query.toLowerCase(),agent=state.node,items=state.transcript.turns.filter(function(t){return(!q||(t.content+" "+t.label).toLowerCase().includes(q))&&(!agent||!t.agent||t.agent===agent);}),list=el("live-transcript-list");el("live-transcript-context").textContent=s?(s.project&&s.project!=="unknown"?s.project:"Project not reported")+" · "+providerName(s):"Select a session to follow";el("live-transcript-clear-filter").hidden=!agent;if(agent)el("live-transcript-clear-filter").textContent="All agents";if(!items.length)list.innerHTML='<div class="live-transcript-empty">'+esc(q?"No matching transcript activity":agent?"No transcript activity attributed to this selection yet.":"Transcript content stays local and appears here as the selected session runs.")+"</div>";else list.innerHTML=items.map(function(t){var fold=t.role==="thinking"||t.role==="tool"||t.role==="tool_result"||t.role==="error",body='<div class="live-turn-body">'+esc(t.content)+"</div>";return'<article class="live-turn" data-role="'+esc(t.role)+'" data-agent="'+esc(t.agent)+'"><div class="live-turn-head"><span>'+esc(t.label||t.role)+'</span><time>'+esc(ago(t.at)||"now")+"</time></div>"+(fold?"<details><summary>Show "+esc(t.role.replace("_"," "))+"</summary>"+body+"</details>":body)+"</article>";}).join("");if(arrived){var near=list.scrollHeight-list.scrollTop-list.clientHeight<56;if(state.transcript.follow||near){list.scrollTop=list.scrollHeight;state.transcript.unread=0;}else state.transcript.unread++;}el("live-transcript-new").hidden=!state.transcript.unread;el("live-transcript-new").textContent=state.transcript.unread+" new activit"+(state.transcript.unread===1?"y":"ies")+" ↓";}
  function stopPlayback(){if(state.playback.timer)clearInterval(state.playback.timer);state.playback.timer=null;state.playback.playing=false;}
  function playbackRecords(){return state.playback.events.length?state.playback.events:state.playback.items;}
  function reviewSession(index){var source=sessionById(state.selected),events=state.playback.events.slice(0,index+1),nodes={},edges={};if(source)nodes[source.id]={id:source.id,kind:"session",host:source.host,status:"running",label:source.title};events.forEach(function(ev){var a=ev.actor||{},t=ev.target||{},tool=ev.tool||{},aid=a.id||source&&source.id,tid=t.id||tool.callId;if(aid){var priorActor=nodes[aid]||{};nodes[aid]=Object.assign({},priorActor,{id:aid,kind:a.kind||(a.role==="tool"?"tool":aid===source.id?"session":"agent"),role:a.role||priorActor.role,label:a.label||priorActor.label,host:source&&source.host,status:ev.status||priorActor.status||"running",observedAt:ev.at});}if(tid){var prior=nodes[tid]||{},nextLabel=t.label||tool.name||tool.category||prior.label;nodes[tid]=Object.assign({},prior,{id:tid,kind:tool.callId?"tool":t.kind||prior.kind||"agent",role:t.role||prior.role,label:nextLabel,toolName:tool.name||prior.toolName,status:tool.status||ev.status||prior.status||"running",durationMs:tool.durationMs||prior.durationMs,observedAt:ev.at});var eid=String(aid+"|"+(tool.callId||tid));edges[eid]={id:eid,source:aid,target:tid,action:ev.relation||ev.kind||"activity"};}});return Object.assign({},source||{},{nodes:Object.keys(nodes).map(function(k){return nodes[k];}),edges:Object.keys(edges).map(function(k){return edges[k];})});}
  function setReviewIndex(index){var p=state.playback,records=playbackRecords(),max=Math.max(0,records.length-1);p.index=Math.max(0,Math.min(max,Number(index)||0));p.session=reviewSession(p.index);var cutoff=records[p.index]&&(records[p.index].at||records[p.index].observedAt||records[p.index].timestamp),items=p.items.filter(function(item,i){var at=item.at||item.observedAt||item.timestamp;return cutoff&&at?Date.parse(at)<=Date.parse(cutoff):i<=Math.round(p.index/Math.max(1,records.length-1)*Math.max(0,p.items.length-1));});addTranscript(items.length?items:records.slice(0,p.index+1),true);renderGraph(p.session);renderPlayback();}
  function renderPlayback(){var p=state.playback,review=p.mode==="review",selected=sessionById(state.selected),active=isLiveSession(selected),records=playbackRecords(),range=el("live-playback-range"),mode=el("live-mode");mode.dataset.mode=review?"review":"live";mode.textContent=review?"REVIEW":"LIVE";el("live-playback").dataset.mode=review?"review":"live";range.disabled=!review||!records.length;range.max=String(Math.max(0,records.length-1));range.value=String(review?p.index:Math.max(0,records.length-1));el("live-playback-toggle").disabled=!review||!records.length;el("live-playback-toggle").innerHTML=p.playing?"&#9208;":"&#9654;";el("live-playback-toggle").setAttribute("aria-label",p.playing?"Pause session review":"Play session review");el("live-enter-review").hidden=review||!active;el("live-resume-live").hidden=!review||!active;var at=records[p.index]&&(records[p.index].observedAt||records[p.index].timestamp||records[p.index].at),stamp=at?new Date(at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit",second:"2-digit"}):"";el("live-playback-time").textContent=review?(stamp||String(Math.min(p.index+1,records.length))+" / "+String(records.length)):"Live now";}
  function loadPlayback(s){closeTranscript();stopPlayback();state.playback={mode:"review",events:[],items:[],index:0,playing:false,speed:state.playback.speed||1,timer:null,startAt:null,endAt:null,session:null,truncated:false,gap:false};transcriptStatus("connecting","Loading review");renderPlayback();fetch("/api/live/playback/"+encodeURIComponent(s.host||providerOf(s))+"/"+encodeURIComponent(s.id),{cache:"no-store"}).then(function(r){if(!r.ok)throw Error();return r.json();}).then(function(v){state.playback.events=Array.isArray(v.events)?v.events:[];state.playback.items=transcriptItems(v.transcript||v.items||[]);state.playback.startAt=v.startAt||null;state.playback.endAt=v.endAt||null;state.playback.truncated=!!v.truncated;state.playback.gap=!!v.gap;var notice=el("live-replay-notice");notice.hidden=!state.playback.truncated&&!state.playback.gap;notice.textContent=state.playback.gap?"Some source events are unavailable; this replay contains an evidence gap.":state.playback.truncated?"Replay begins at the earliest retained local evidence.":"";var records=playbackRecords();setReviewIndex(Math.max(0,records.length-1));transcriptStatus("review","Review");}).catch(function(){state.playback.items=[];state.playback.events=[];state.transcript.turns=[];renderTranscript();transcriptStatus("error","Review unavailable");renderPlayback();});}
  function resumeLive(){var s=sessionById(state.selected);stopPlayback();state.playback.mode="live";state.playback.events=[];state.playback.items=[];state.playback.session=null;if(isLiveSession(s))openTranscript(s);else if(s)loadPlayback(s);render();}
  function selectSession(id,open){var s=sessionById(id),key=s?sessionKey(s):id;if(state.selected===key&&state.transcript.session===key)return;stopPlayback();state.selected=key||null;state.node=null;state.fitFor=null;state.camera={x:24,y:24,k:1};if(open!==false){if(isLiveSession(s)){state.playback.mode="live";openTranscript(s);}else if(s)loadPlayback(s);}}
  function selectNode(id){state.node=id||null;render();renderTranscript();}
  function bind(){
    el("live-pause").addEventListener("click",function(){state.paused=!state.paused;this.setAttribute("aria-pressed",String(state.paused));this.innerHTML=state.paused?"&#9654; Resume":"&#9208; Pause";if(!state.paused){var q=state.pending.slice();state.pending=[];if(state.overflow){state.overflow=false;connect();}else q.forEach(function(p){receive(p.kind,p.data);});}});
    el("live-health-toggle").addEventListener("click",function(){var h=el("live-health"),open=h.hidden;h.hidden=!open;this.setAttribute("aria-expanded",String(open));if(open){var r=this.getBoundingClientRect(),w=Math.min(360,window.innerWidth-24);h.style.width=w+"px";h.style.left=Math.max(12,Math.min(window.innerWidth-w-12,r.right-w))+"px";h.style.top=Math.min(window.innerHeight-h.offsetHeight-12,r.bottom+8)+"px";}});
    el("live-project-list").addEventListener("click",function(e){var b=e.target.closest("[data-project]");if(!b)return;state.project=b.dataset.project;state.browserLevel="sessions";var list=visibleSessions();selectSession(list[0]&&sessionKey(list[0]));render();(el("live-session-list").querySelector("[data-session]")||el("live-browser-back")).focus();});
    el("live-browser-back").addEventListener("click",function(){state.browserLevel="projects";renderSessions();var selectedProject=el("live-project-list").querySelector('[data-project="'+CSS.escape(state.project||"")+'"]');if(selectedProject)selectedProject.focus();});
    el("live-session-list").addEventListener("click",function(e){var b=e.target.closest("[data-session]");if(b){selectSession(b.dataset.key||b.dataset.session);render();}});
    el("live-playback-range").addEventListener("input",function(){stopPlayback();setReviewIndex(this.value);});
    el("live-playback-speed").addEventListener("change",function(){state.playback.speed=Number(this.value)||1;if(state.playback.playing){stopPlayback();el("live-playback-toggle").click();}});
    el("live-playback-toggle").addEventListener("click",function(){var p=state.playback,records=playbackRecords();if(p.mode!=="review"||!records.length)return;if(p.playing){stopPlayback();renderPlayback();return;}if(p.index>=records.length-1)setReviewIndex(0);p.playing=true;function advance(){if(!p.playing)return;if(p.index>=records.length-1){stopPlayback();renderPlayback();return;}var here=Date.parse(records[p.index]&&(records[p.index].at||records[p.index].observedAt||records[p.index].timestamp)||0),next=Date.parse(records[p.index+1]&&(records[p.index+1].at||records[p.index+1].observedAt||records[p.index+1].timestamp)||0),delay=Number.isFinite(here)&&Number.isFinite(next)?Math.max(90,Math.min(1800,(next-here)/p.speed)):Math.max(120,700/p.speed);p.timer=setTimeout(function(){setReviewIndex(p.index+1);advance();},delay);}advance();renderPlayback();});
    el("live-enter-review").addEventListener("click",function(){var s=sessionById(state.selected);if(s)loadPlayback(s);});
    el("live-resume-live").addEventListener("click",resumeLive);
    el("live-zoom-in").onclick=function(){setZoom(state.camera.k*1.2);};el("live-zoom-out").onclick=function(){setZoom(state.camera.k/1.2);};el("live-fit").onclick=function(){state.cameraEpoch++;fit();};el("live-fit-selection").onclick=fitSelection;el("live-reset-layout").onclick=function(){var s=sessionById(state.selected);delete state.positions[s?s.id:"none"];state.pinned={};renderGraph(s,true);fit();};
    el("live-transcript-search").addEventListener("input",function(){state.transcript.query=this.value;renderTranscript();});el("live-transcript-list").addEventListener("scroll",function(){var near=this.scrollHeight-this.scrollTop-this.clientHeight<56;if(!near&&state.transcript.follow){state.transcript.follow=false;el("live-transcript-follow").setAttribute("aria-pressed","false");el("live-transcript-follow").textContent="Follow";}});el("live-transcript-follow").onclick=function(){state.transcript.follow=!state.transcript.follow;this.setAttribute("aria-pressed",String(state.transcript.follow));this.textContent=state.transcript.follow?"Following":"Follow";if(state.transcript.follow){var l=el("live-transcript-list");l.scrollTop=l.scrollHeight;state.transcript.unread=0;renderTranscript();}};el("live-transcript-clear-filter").onclick=function(){selectNode(null);};el("live-transcript-new").onclick=function(){state.transcript.follow=true;el("live-transcript-follow").setAttribute("aria-pressed","true");el("live-transcript-follow").textContent="Following";var l=el("live-transcript-list");l.scrollTop=l.scrollHeight;state.transcript.unread=0;renderTranscript();};
    var canvas=el("live-canvas"),graph=el("live-graph");canvas.addEventListener("wheel",function(e){e.preventDefault();setZoom(state.camera.k*Math.exp(-e.deltaY*.0015),e.clientX,e.clientY);},{passive:false});
    canvas.addEventListener("pointerdown",function(e){var n=e.target.closest&&e.target.closest("[data-node]");state.cameraEpoch++;state.pointer={id:e.pointerId,x:e.clientX,y:e.clientY,sx:e.clientX,sy:e.clientY,moved:false,node:n&&n.dataset.node};canvas.setPointerCapture(e.pointerId);canvas.dataset.panning=String(!n);});
    canvas.addEventListener("pointermove",function(e){var p=state.pointer;if(!p||p.id!==e.pointerId)return;var dx=e.clientX-p.x,dy=e.clientY-p.y;if(Math.abs(e.clientX-p.sx)+Math.abs(e.clientY-p.sy)>4)p.moved=true;if(p.node){var s=sessionById(state.selected),positions=state.positions[s?s.id:"none"],at=positions&&positions[p.node];if(at){at.x+=dx/state.camera.k;at.y+=dy/state.camera.k;state.pinned[(s?s.id:"")+"|"+p.node]=true;updateGeometry(p.node);}}else{state.camera.x+=dx;state.camera.y+=dy;applyCamera();}p.x=e.clientX;p.y=e.clientY;});
    function up(e){var p=state.pointer;if(!p||p.id!==e.pointerId)return;state.pointer=null;canvas.removeAttribute("data-panning");if(p.node&&!p.moved)selectNode(p.node);}canvas.addEventListener("pointerup",up);canvas.addEventListener("pointercancel",up);
    graph.addEventListener("dblclick",function(e){var n=e.target.closest&&e.target.closest(".live-node");if(!n)return;var s=sessionById(state.selected);delete state.pinned[(s?s.id:"")+"|"+n.dataset.node];n.dataset.pinned="false";});
    graph.addEventListener("keydown",function(e){var n=e.target.closest&&e.target.closest("[data-node]");if(!n)return;if(e.key==="Enter"||e.key===" "){selectNode(n.dataset.node);e.preventDefault();}});
    canvas.addEventListener("keydown",function(e){if(e.target.closest&&e.target.closest("[data-node]"))return;var ok=true;if(e.key==="+"||e.key==="=")setZoom(state.camera.k*1.2);else if(e.key==="-"||e.key==="_")setZoom(state.camera.k/1.2);else if(e.key.toLowerCase()==="f")fit();else if(e.key==="0"){state.camera={x:24,y:24,k:1};applyCamera();}else ok=false;if(ok)e.preventDefault();});document.addEventListener("keydown",function(e){if(e.key==="Escape"&&!el("live-health").hidden){el("live-health").hidden=true;el("live-health-toggle").setAttribute("aria-expanded","false");el("live-health-toggle").focus();}});document.addEventListener("pointerdown",function(e){var h=el("live-health"),b=el("live-health-toggle");if(!h.hidden&&!h.contains(e.target)&&!b.contains(e.target)){h.hidden=true;b.setAttribute("aria-expanded","false");}});
  }
  function activate(){state.active=true;if(!state.source)connect();render();}function deactivate(){state.active=false;if(state.source){state.source.close();state.source=null;}stopPlayback();closeTranscript();setConnection("offline","Live view inactive");}
  bind();setInterval(function(){if(state.active&&!state.paused&&state.lastAt&&Date.now()-state.lastAt>30000)setConnection("stale","Connected · no new activity for 30 seconds");},5000);
  window.AKLive={activate:activate,deactivate:deactivate,render:render,receive:receive,state:state,fit:fit,fitSelection:fitSelection,selectNode:selectNode,addTranscript:addTranscript};
})();`;
