import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {
  AQE_GUARD_SLUG,
  PROJECT_GUIDANCE_SLUG,
  captureProjectGuidance,
  legacyLeanProjectGuidance,
  reconcileProjectGuidance,
} from '../../src/lib/project-guidance.mjs';

const fixture = (t) => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'ak-project-guidance-'));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  return root;
};

const simulateUpstreams = (root) => {
  fs.writeFileSync(path.join(root, 'CLAUDE.md'), '# generated by upstream\n');
};

test('no prior guidance and AQE disabled leaves no project prompt file', (t) => {
  const root = fixture(t);
  const prior = captureProjectGuidance(root);
  simulateUpstreams(root);

  const result = reconcileProjectGuidance({ root, prior, aqeEnabled: false });
  assert.equal(result.action, 'removed-generated');
  assert.equal(fs.existsSync(path.join(root, 'CLAUDE.md')), false);
});

test('an AGENTS-only project gets one tiny Claude import instead of copied instructions', (t) => {
  const root = fixture(t);
  fs.writeFileSync(path.join(root, 'AGENTS.md'), '# User-owned repository rules\n');
  const prior = captureProjectGuidance(root);
  simulateUpstreams(root);

  reconcileProjectGuidance({ root, prior, aqeEnabled: true });
  const content = fs.readFileSync(path.join(root, 'CLAUDE.md'), 'utf8');
  assert.match(content, /@AGENTS\.md/);
  assert.doesNotMatch(content, /User-owned repository rules/);
  assert.equal((content.match(new RegExp(`BEGIN ${PROJECT_GUIDANCE_SLUG}`, 'g')) ?? []).length, 1);
  assert.equal((content.match(new RegExp(`BEGIN ${AQE_GUARD_SLUG}`, 'g')) ?? []).length, 1);
});

test('existing CLAUDE.md and AGENTS.md remain user-owned without hidden composition', (t) => {
  const root = fixture(t);
  fs.writeFileSync(path.join(root, 'CLAUDE.md'), '# Claude-specific user rules\n');
  fs.writeFileSync(path.join(root, 'AGENTS.md'), '# Codex-specific user rules\n');
  const prior = captureProjectGuidance(root);
  simulateUpstreams(root);

  reconcileProjectGuidance({ root, prior, aqeEnabled: true });
  const content = fs.readFileSync(path.join(root, 'CLAUDE.md'), 'utf8');
  assert.match(content, /Claude-specific user rules/);
  assert.doesNotMatch(content, /@AGENTS\.md/);
  assert.doesNotMatch(content, /generated by upstream/);
  assert.equal(fs.readFileSync(path.join(root, 'AGENTS.md'), 'utf8'), '# Codex-specific user rules\n');
});

test('legacy non-sentineled lean stub migrates without deleting adjacent user text', (t) => {
  const root = fixture(t);
  const legacy = legacyLeanProjectGuidance(path.basename(root));
  fs.writeFileSync(path.join(root, 'CLAUDE.md'), `${legacy}\n# Keep this user section\n`);
  const prior = captureProjectGuidance(root);
  simulateUpstreams(root);

  reconcileProjectGuidance({ root, prior, aqeEnabled: false });
  const content = fs.readFileSync(path.join(root, 'CLAUDE.md'), 'utf8');
  assert.doesNotMatch(content, /hierarchical-mesh|Full ruflo reference/);
  assert.match(content, /Keep this user section/);
});

test('repeat reconciliation is byte-idempotent and converges duplicate managed blocks', (t) => {
  const root = fixture(t);
  fs.writeFileSync(path.join(root, 'AGENTS.md'), '# Rules\n');
  const firstPrior = captureProjectGuidance(root);
  simulateUpstreams(root);
  reconcileProjectGuidance({ root, prior: firstPrior, aqeEnabled: true });
  const once = fs.readFileSync(path.join(root, 'CLAUDE.md'), 'utf8');

  const duplicate = `${once}\n${once}`;
  fs.writeFileSync(path.join(root, 'CLAUDE.md'), duplicate);
  const repeatedPrior = captureProjectGuidance(root);
  simulateUpstreams(root);
  reconcileProjectGuidance({ root, prior: repeatedPrior, aqeEnabled: true });
  const converged = fs.readFileSync(path.join(root, 'CLAUDE.md'), 'utf8');
  assert.equal((converged.match(new RegExp(`BEGIN ${PROJECT_GUIDANCE_SLUG}`, 'g')) ?? []).length, 1);
  assert.equal((converged.match(new RegExp(`BEGIN ${AQE_GUARD_SLUG}`, 'g')) ?? []).length, 1);

  const finalPrior = captureProjectGuidance(root);
  simulateUpstreams(root);
  reconcileProjectGuidance({ root, prior: finalPrior, aqeEnabled: true });
  assert.equal(fs.readFileSync(path.join(root, 'CLAUDE.md'), 'utf8'), converged);
});

test('disabling AQE strips only the agentic-kit guard and preserves user prior art', (t) => {
  const root = fixture(t);
  fs.writeFileSync(path.join(root, 'CLAUDE.md'), '# User rules\n\n## Agentic QE v3 custom notes\n');
  const prior = captureProjectGuidance(root);
  simulateUpstreams(root);
  reconcileProjectGuidance({ root, prior, aqeEnabled: true });
  const withPriorArt = fs.readFileSync(path.join(root, 'CLAUDE.md'), 'utf8');
  assert.equal((withPriorArt.match(/## Agentic QE v3/g) ?? []).length, 1,
    'an existing user heading suppresses a redundant guard');

  const disabledPrior = captureProjectGuidance(root);
  simulateUpstreams(root);
  reconcileProjectGuidance({ root, prior: disabledPrior, aqeEnabled: false });
  const disabled = fs.readFileSync(path.join(root, 'CLAUDE.md'), 'utf8');
  assert.match(disabled, /Agentic QE v3 custom notes/);
  assert.doesNotMatch(disabled, new RegExp(`BEGIN ${AQE_GUARD_SLUG}`));
});
